# Generated by Django 5.2.6 on 2025-09-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
